[package]
name = "adventure_game"
version = "0.1.0"
authors = ["ando-huang <ahuang09182000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "adventure_game"
path = "main.rs"
